### PR TITLE
feature: v1

### PR DESCRIPTION
**Pull request by marlonmarcello**
# Goal

Masher V1!
This initial work is mostly conversion and refactoring. A lot of the logic was kept intact with some improvements here and there.

### Timing
I am not able to spend much more time refactoring this as we need V1 ready to continue work on Corgi and Component Library, so please focus your test on potential bugs and incompatibilities.

With the hardest part in place we can keep track of changes and features in Issues from here on out.

### Picture component

I added the `Picture` component to the repo with the intention of releasing it soon. I have a ticket create for it so we can keep track of that feature #2 but please ignore it for now.

## Testing

You don't need a Corgi project to test this.

1. Clone this repo and checkout `feature/v1`
2. Make sure you are running the correct node version and `npm install`
3. `npm run build`
4. `npm link`

You are now ready to test
1. `mkdir my-test`
5. `cd my-test`
6. `npm init -y`
7. `npm link @wethegit/masher`
8. `mkdir -p src/images/defined/`
9. Add a few images to the `defined` directory created above
10. Run the masher `npx @wethegit/masher`
11. For watching for changes `npx @wethegit/masher --watch`

After running the masher you should see the compressed images in a `public/_images/` directory. You can change the input and output directories inside the `masher.config.json` file gets created after you ran it at least once.

### CODE REVIEW

**Comment by andrewrubin** [comment]
Hey @marlonmarcello, I'm having trouble testing this one. 
- Tried running it via npx, and got `sh: masher: command not found`

Lmk if I can help debug at all.

I think we could also maybe add an `.npmignore` for some of the stuff in the final package output. Whaddaya think?

Thanks

**Comment by marlonmarcello** [comment]
@andrewrubin use `@wethegit/masher` not `masher`. Step `7` on the instructions above, you need the namespace

**Comment by marlonmarcello** [comment]
> I think we could also maybe add an `.npmignore` for some of the stuff in the final package output. Whaddaya think?

Already added a `.npmignore`, did I miss anything there?

**Comment by andrewrubin** [comment]
Hmm, I am running `npx @wethegit/masher`, I get the error like it's trying to run a shell script 🤔 

Screen Shot 2024-01-15 at 4 31 15 PM

**Comment by andrewrubin** [comment]
Oh, I didn't build the package.

**Comment by marlonmarcello** [comment]
Ooh, missed that step, my bad!

**Comment by andrewrubin** [comment]
Tested and working well, thanks!

Just a couple notes:
- Should I be testing the `picture` React component for this review?
- I'm not seeing the ignored files actually being ignored — is this maybe just because it's via npm link instead of a published package?

**Comment by marlonmarcello** [comment]
Thanks @andrewrubin !

> Should I be testing the picture React component for this review?

You can, as per my comment on the PR body, it's not ready. But you can test the one on Corgi to make sure this didn't break that.

> I'm not seeing the ignored files actually being ignored — is this maybe just because it's via npm link instead of a published package?

Do you mean for the NPM package itself? If so that's expected. `link` just basically creates a symbolical link of the whole thing.

**Comment by andrewrubin** [comment]
Okay cool, thanks. Been a while since I last set up a new package for publishing, so wasn't sure how the `.npmignore` works.

`<Picture>` will need some tweaks, but I won't let that block this PR. Like you said, we can make issues for Picture specifically.
- image output now lives in `_images/defined`, whereas `picture` expects it in `_images/`
- The masher-register import path is relative, this will likely need to be aliased I'd imagine.

**Review by andrewrubin — APPROVED** [review]

**Comment by marlonmarcello** [comment]
> * image output now lives in `_images/defined`, whereas `picture` expects it in `_images/`

You can just delete `defined/` we don't have multiple "modes" anymore. Just the default.

**Comment by marlonmarcello** [comment]
Thanks for the review!

**Comment by marlonmarcello** [comment]
> The masher-register import path is relative, this will likely need to be aliased I'd imagine.

Maybe we output this file inside `src/` so we can easily use the alias we have and do `@local/register.json`

**Pull request merged**
